# Generated by Django 5.0.2 on 2024-12-07 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('house_name', models.CharField(default='', max_length=100)),
                ('house_furnishing', models.CharField(default='', max_length=50)),
                ('house_carpet_area', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('house_no_bedrooms', models.IntegerField(default=0)),
                ('house_no_bathrooms', models.IntegerField(default=0)),
                ('house_overlooking', models.CharField(max_length=30)),
                ('house_floor_no', models.IntegerField(default=0)),
                ('house_owner_name', models.CharField(default='', max_length=100)),
                ('house_owner_number', models.CharField(default='', max_length=15)),
                ('house_owner_mail', models.EmailField(default='', max_length=100)),
                ('house_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('house_description', models.CharField(default='', max_length=300)),
                ('images1', models.ImageField(default='', upload_to='images')),
                ('images2', models.ImageField(default='', upload_to='images')),
                ('images3', models.ImageField(default='', upload_to='images')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comments_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
